// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LinkOrderToProduct struct {
	ID        int64  `db:"id" json:"id"`
	OrderID   *int64 `db:"order_id" json:"order_id"`
	ProductID *int64 `db:"product_id" json:"product_id"`
	Count     int64  `db:"count" json:"count"`
}

type Order struct {
	ID          int64            `db:"id" json:"id"`
	UserID      pgtype.UUID      `db:"user_id" json:"user_id"`
	AppendDate  pgtype.Timestamp `db:"append_date" json:"append_date"`
	TotalAmount pgtype.Numeric   `db:"total_amount" json:"total_amount"`
}

type Product struct {
	ID    int64          `db:"id" json:"id"`
	Name  string         `db:"name" json:"name"`
	Price pgtype.Numeric `db:"price" json:"price"`
}

type User struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Name     string      `db:"name" json:"name"`
	Email    string      `db:"email" json:"email"`
	Password string      `db:"password" json:"password"`
}
