// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	LinkOrderToProductByOrderId(ctx context.Context, orderID *int64) ([]*LinkOrderToProduct, error)
	LinkOrderToProductCreate(ctx context.Context, arg LinkOrderToProductCreateParams) (int64, error)
	OrderById(ctx context.Context, arg OrderByIdParams) (*Order, error)
	OrderCreate(ctx context.Context, arg OrderCreateParams) (int64, error)
	OrderUpdateTotalAmount(ctx context.Context, arg OrderUpdateTotalAmountParams) (int64, error)
	Orders(ctx context.Context, arg OrdersParams) ([]*Order, error)
	ProductCreate(ctx context.Context, arg ProductCreateParams) (int64, error)
	ProductUpdatePrice(ctx context.Context, arg ProductUpdatePriceParams) (int64, error)
	Products(ctx context.Context, arg ProductsParams) ([]*Product, error)
	ProductsByIds(ctx context.Context, arg ProductsByIdsParams) ([]*Product, error)
	UserById(ctx context.Context, arg UserByIdParams) (*User, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (pgtype.UUID, error)
	Users(ctx context.Context, arg UsersParams) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
