version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18  # Используется образ PostgreSQL версии 14.8 на Alpine Linux
    environment:
      POSTGRES_DB: "homeworkdb"  # Имя базы данных, которая будет создана при запуске контейнера
      POSTGRES_USER: "homeworkpguser"  # Имя пользователя, который будет создан
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"  # Каталог для данных PostgreSQL
    ports:
      - "5432:5432"  # Проброс порта 5432 контейнера на порт 5432 хоста
    restart: unless-stopped
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d  # Монтирование директории с SQL-скриптами для инициализации
      - hw14_sql_data:/var/lib/postgresql/data  # Монтирование тома для хранения данных
      - ./data:/var/lib/postgresql/data  # Монтирование тома для хранения данных
    networks:
      - my_network

volumes:
  hw14_sql_data:

networks:
  my_network: